### ISSUE TITLE
Updated NuGet package

### ISSUE THREAD

**Issue by bslatner** [erezak/libphonenumber-csharp#17]
I see some changes have been made since the most recent publication of the package on NuGet. Are you going to deploy those as an updated package?

**Comment by elijajah** [comment]
There are problems with this library as it stands today. Notably, many of the built-in tests (ported from Java) are failing. This is due to the library lagging behind the original Java source, while the metadata keeps getting updated. (For instance, short numbers have been moved to a separate .XML file, which is being ignored by the C# code.)

**Comment by erezak** [comment]
Yes, I'm trying to set some time to update both the issues and the package soon.

**Comment by elijajah** [comment]
@erezak: hey thanks!! It would be really nice if we could help out with this.

(ps. my fork of your repo restructures the usage so it doesn't rely on exceptions as part of the library's flow. This saves a bunch of performance hits, which are crucial to using the lib on Windows Phone.)

**Comment by mstrong64** [comment]
@elijajah - I'd love to use this code without the exception based flow!

**Comment by mstyura** [comment]
@erezak it would be nice to have and update of nuget package. Thanks in advance.
